name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Install llvm
      shell: bash
      run: sudo apt-get update && sudo apt-get install llvm-dev --no-install-recommends
    - name: Build
      shell: bash
      run: cmake -Bbin -GNinja -DXCFT_BUILD_SHARED=OFF && cmake --build bin 
      
